version: '3.8'

services:
  app:
    build: .
    env_file:
      - stack.env
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - stack.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
