name: Build Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build API Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/api:latest

      - name: Build GUI Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./gui.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/gui:latest
